routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('landing');


Auth::routes();


Route::group(['namespace' =>"App\Http\Controllers"], function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'auth'], function (){
       Route::patch("/user/{id}", "UserController@update")->name("update-profile");
       Route::patch("/user/password/{id}", "UserController@updatePassword")->name("update-password");
    });



    Route::group(['prefix'  => 'admin', 'middleware'=>['auth', 'admin']], function(){
        Route::get('/', 'HomeController@admin')->name('admin');

        Route::resource('banner', "BannerController")->except('show');
    });

    Route::group(['prefix'  => 'customer', 'middleware'=>['auth', 'customer']], function(){
        Route::get('/', 'HomeController@customer')->name('customer');
    });

    Route::group(['prefix'  => 'seller', 'middleware'=>['auth', 'seller']], function(){
        Route::get('/', 'HomeController@seller')->name('seller');
    });
});

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    use HasFactory;

    protected  $fillable = ['title', 'link', 'image', 'status', 'created_by'];

    public function bannerValidateRules($act = 'add'){
        return $rules = [
            'title'         => 'required|string|max:150',
            'link'          => 'required|url',
            //'image'         => ($act == 'add' ? 'required|' : 'sometimes|')."image|max:7000",
            'status'        => 'required|in:active,inactive',

        ];
    }
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Banner;
use Illuminate\Http\Request;

class BannerController extends Controller
{
    protected $banner = null;
    public function __construct(Banner $banner)
    {
        $this->banner = $banner;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.banner.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.banner.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = $this->banner->bannerValidateRules();
        $request->validate($rules);

        $data = $request->except('image');

        /*$image_name = uploadImage($request->image, 'banner', '1200x300');
        if($image_name){
            $data['image'] = $image_name;
        }*/

        $this->banner->fill($data);
        $status = $this->banner->save();
        if($status){
            $request->session()->flash('success', 'Banner created successfully');
        }else{
            $request->session()->flash('error', 'Sorry! There was problem while creating banner.');
        }

        return redirect()->route('banner.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/banner/form.blade.php
@extends('layouts.admin')
@section('title','Banner Creare, Admin || Dashboard')
@section('main-content')

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Banner Form</div>
                    <div class="ibox-tools">
                        <a href="{{ route('banner.create') }}" class="btn  btn-sm btn-success">
                            <i class="fa fa-plus"></i> Create Banner
                        </a>
                    </div>
                </div>
                <div class="ibox-body">
                    {{ Form::open(['url' =>route('banner.store'), 'class' =>'form', 'files' => true]) }}
                        <div class="form-group row">
                            {{ Form::label('title', 'Title: ', ['class' => 'col-sm-12 col-md-3']) }}
                            <div class="col-sm-12 col-md-9">
                                {{ Form::text('title', '', ['class'=>'form-control form-control-sm', 'id'=>'title',
                                    'required'=>true, 'placeholder' =>'Enter banner title here.']) }}
                                @error('title')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>

                    <div class="form-group row">
                        {{ Form::label('link', 'URL: ', ['class' => 'col-sm-12 col-md-3']) }}
                        <div class="col-sm-12 col-md-9">
                            {{ Form::url('link', '', ['class'=>'form-control form-control-sm', 'id'=>'link',
                                'required'=>true, 'placeholder' =>'Enter banner link here.']) }}
                            @error('link')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('status', 'Status: ', ['class' => 'col-sm-12 col-md-3']) }}
                        <div class="col-sm-12 col-md-9">
                            {{ Form::select('status', ['active' =>'Published', 'inactive'=> 'Un-published'],
                                ['class'=>'form-control form-control-sm', 'id'=>'status', 'required'=>true]) }}
                            @error('status')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('image', 'Status: ', ['class' => 'col-sm-12 col-md-3']) }}
                        <div class="col-sm-12 col-md-9">
                            {{ Form::file('image',['id'=>'image', 'accept'=>'image/*']) }}
                            @error('image')
                            <span class="text-danger">{{ $message }}</span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <div class="offset-md-3 col-sm-12 col-md-9">
                            {{ Form::button("<i class='fa fa-trash'></i> Reset", ['class' => 'btn btn-sm btn-danger', 'type'=>'reset']) }}
                            {{ Form::button("<i class='fa fa-paper-plane'></i> Submit", ['class' => 'btn btn-sm btn-success', 'type'=>'submit']) }}
                        </div>
                    </div>


                    {{ Form::close() }}
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/banner/index.blade.php
@extends('layouts.admin')
@section('title','Banner Page, Admin || Dashboard')
@section('main-content')

    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-head">
                    <div class="ibox-title">Banner List</div>
                    <div class="ibox-tools">
                        <a href="{{ route('banner.create') }}" class="btn  btn-sm btn-success">
                            <i class="fa fa-plus"></i> Create Banner
                        </a>
                    </div>
                </div>
                <div class="ibox-body">
                    <table class="table table-striped table-hover">
                        <thead>
                            <th>Title</th>
                            <th>Link</th>
                            <th>Image</th>
                            <th>Status</th>
                            <th>Created By</th>
                            <th>Action</th>
                        </thead>
                        <tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection