routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('landing');


Auth::routes();


Route::group(['namespace' =>"App\Http\Controllers"], function(){
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['middleware' => 'auth'], function (){
       Route::patch("/user/{id}", "UserController@update")->name("update-profile");
       Route::patch("/user/password/{id}", "UserController@updatePassword")->name("update-password");
    });



    Route::group(['prefix'  => 'admin', 'middleware'=>['auth', 'admin']], function(){
        Route::get('/', 'HomeController@admin')->name('admin');

        Route::resource('banner', "BannerController")->except('show');
    });

    Route::group(['prefix'  => 'customer', 'middleware'=>['auth', 'customer']], function(){
        Route::get('/', 'HomeController@customer')->name('customer');
    });

    Route::group(['prefix'  => 'seller', 'middleware'=>['auth', 'seller']], function(){
        Route::get('/', 'HomeController@seller')->name('seller');
    });
});

resources/views/admin/partials/copy.blade.php
<footer class="page-footer">
    <a class="px-4" href="http://themeforest.net/item/adminca-responsive-bootstrap-4-3-angular-4-admin-dashboard-template/20912589" target="_blank">By OurCommerce</a>
    <div class="to-top"><i class="fa fa-angle-double-up"></i></div>
</footer>

resources/views/admin/partials/notify.blade.php
@if(session('success'))
    <div class="alert alert-success alert-bordered alert-dismissable fade show">
        <button class="close" data-dismiss="alert" aria-label="Close">x</button>
        {{ session('success') }}
    </div>
@endif

@if(session('error'))
    <div class="alert alert-danger alert-bordered alert-dismissable fade show">
        <button class="close" data-dismiss="alert" aria-label="Close">x</button>
        {{ session('error') }}
    </div>
@endif

@if(session('warning'))
    <div class="alert alert-warning alert-bordered alert-dismissable fade show">
        <button class="close" data-dismiss="alert" aria-label="Close">x</button>
        {{ session('warning') }}
    </div>
@endif

resources/views/admin/partials/scripts.blade.php
<div class="sidenav-backdrop backdrop"></div>
<div class="preloader-backdrop">
    <div class="page-preloader">Loading</div>
</div>
<!-- END PAGA BACKDROPS-->
<!-- CORE PLUGINS-->

<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ mix('js/admin.js') }}"></script>
@yield('scripts')
</body>

</html>

resources/views/admin/partials/side-bar.blade.php
<!-- START SIDEBAR-->
<nav class="page-sidebar" id="sidebar">
    <div id="sidebar-collapse">
        <div class="admin-block d-flex">
            <div>
                @if(auth()->user()->userInfo!= null && auth()->user()->userInfo->image != null &&
                        file_exists(public_path().'/uploads/user/'.auth()->user()->userInfo->image))
                    <img src="{{ asset('uploads/user/'.auth()->user()->userInfo->image) }}" width="45px" class="img img-fluid img-cirlcl" />
                @else
                    <img src="{{ asset('images/user.png') }}" alt="" width="45px" class="img img-fluid img-circle">
                @endif
            </div>
            <div class="admin-info">
                <div class="font-strong">{{ auth()->user()->name }}</div><small>{{ ucfirst(auth()->user()->role) }}</small></div>
        </div>
        <ul class="side-menu metismenu">
            <li>
                <a class="active" href="{{ route(auth()->user()->role) }}"><i class="sidebar-item-icon fa fa-th-large"></i>
                    <span class="nav-label">Dashboard</span>
                </a>
            </li>
            <li class="heading">FEATURES</li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-images"></i>
                    <span class="nav-label">Banner Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="{{ route('banner.index') }}">List Banner</a>
                    </li>
                    <li>
                        <a href="{{ route('banner.create') }}">Add Banner</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-sitemap"></i>
                    <span class="nav-label">Category Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-bold"></i>
                    <span class="nav-label">Brand Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-users"></i>
                    <span class="nav-label">User Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-shopping-basket"></i>
                    <span class="nav-label">Product Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-shopping-cart"></i>
                    <span class="nav-label">Order Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-comments"></i>
                    <span class="nav-label">Review Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-gifts"></i>
                    <span class="nav-label">Collections Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-newspaper"></i>
                    <span class="nav-label">Blog Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="javascript:;">
                    <i class="sidebar-item-icon fa fa-file"></i>
                    <span class="nav-label">Pages Manager</span>
                    <i class="fa fa-angle-left arrow"></i>
                </a>
                <ul class="nav-2-level collapse">
                    <li>
                        <a href="colors.html">Colors</a>
                    </li>
                    <li>
                        <a href="typography.html">Typography</a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</nav>
<!-- END SIDEBAR-->

resources/views/admin/partials/top-header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <title>@yield('title')</title>

    <link rel="stylesheet" href="{{ mix('css/admin.css') }}">
    @yield('styles')
</head>

<body class="fixed-navbar">

resources/views/admin/partials/top-menu.blade.php
<!-- START HEADER-->
<header class="header">
    <div class="page-brand">
        <a class="link" href="{{ route('landing') }}" target="_new">
            <span class="brand">Our
                <span class="brand-tip">Commerce</span>
            </span>
            <span class="brand-mini">OC</span>
        </a>
    </div>
    <div class="flexbox flex-1">
        <!-- START TOP-LEFT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li>
                <a class="nav-link sidebar-toggler js-sidebar-toggler"><i class="ti-menu"></i></a>
            </li>
        </ul>
        <!-- END TOP-LEFT TOOLBAR-->
        <!-- START TOP-RIGHT TOOLBAR-->
        <ul class="nav navbar-toolbar">
            <li class="dropdown dropdown-user">
                <a class="nav-link dropdown-toggle link" data-toggle="dropdown">
                    @if(auth()->user()->userInfo!= null && auth()->user()->userInfo->image != null &&
                        file_exists(public_path().'/uploads/user/'.auth()->user()->userInfo->image))
                    <img src="{{ asset('uploads/user/'.auth()->user()->userInfo->image) }}" />
                    @else
                        <img src="{{ asset('images/user.png') }}" alt="">
                    @endif
                    <span></span>
                    {{ auth()->user()->name }}
                    <i class="fa fa-angle-down m-l-5"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">

                    <a class="dropdown-item edit-profile" href="javascript:;" onclick=""><i class="fa fa-user"></i>Profile</a>

                    <a class="dropdown-item" href="javascript:;" data-target="#change-pwd" data-toggle="modal"><i class="fa fa-key"></i>Change Password</a>
                    <li class="dropdown-divider"></li>
                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                    document.getElementById('logoutform').submit();"><i class="fa fa-power-off"></i>Logout</a>
                    {{ Form::open(['url' => route('logout'), 'id' => 'logoutform']) }}
                    {{ Form::close() }}
                </ul>
            </li>
        </ul>
        <!-- END TOP-RIGHT TOOLBAR-->
    </div>
</header>
<!-- END HEADER-->

<---- Change Password Modal ---->
<div class="modal fade" id="change-pwd" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editProfileLabel">Update User Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{ Form::open(['url'=>route('update-password', auth()->user()->id), 'files'=>true ]) }}
            @method('patch')
            <div class="modal-body">
                <div class="form-group row">
                    {{ Form::label('password', 'Password:', ['class' => 'col-sm-3']) }}
                    <div class="col-sm-9">
                        {{ Form::password('password', ['class' =>'form-control form-control-sm',
                        'required'=>true, 'id' => 'password', 'placeholder'=>'Enter Your New Password']) }}
                    </div>
                </div>

                <div class="form-group row">
                    {{ Form::label('password_confirmation', 'Confirm Password:', ['class' => 'col-sm-3']) }}
                    <div class="col-sm-9">
                        {{ Form::password('password_confirmation', ['class' =>'form-control form-control-sm',
                        'required'=>true, 'id' => 'password_confirmation', 'placeholder'=>'Re-Enter Your New Password']) }}
                        <span class="alert-danger" id="error_password"></span>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="reset" class="btn btn-danger" data-dismiss="modal">
                    <i class="fa fa-redo"></i>
                    Reset
                </button>
                <button type="submit" class="btn btn-success" id="submit">
                    <i class="fa fa-paper-plane"></i>
                    Save changes
                </button>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>


<---- Update Profile Modal ---->
<div class="modal fade" id="editProfile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editProfileLabel">Update User Profile</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {{ Form::open(['url'=>route('update-profile', auth()->user()->id), 'files'=>true ]) }}
            @method('patch')
                <div class="modal-body">
                    <div class="form-group row">
                        {{ Form::label('name', 'Name:', ['class' => 'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::text('name', auth()->user()->name, ['class' =>'form-control form-control-sm',
                            'required'=>true, 'id' => 'name', 'placeholder'=>'Enter Your Name']) }}
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('phone', 'Phone:', ['class' => 'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::tel('phone', (auth()->user()->userInfo != null)?auth()->user()->userInfo->phone: null, ['class' =>'form-control form-control-sm',
                            'required'=>false, 'id' => 'phone', 'placeholder'=>'Enter Your Phone Number']) }}
                        </div>
                    </div>
                    <div class="form-group row">
                        {{ Form::label('address', 'Address:', ['class' => 'col-sm-3']) }}
                        <div class="col-sm-9">
                            {{ Form::text('address', (auth()->user()->userInfo != null)?auth()->user()->userInfo->address: null,
                                ['class' =>'form-control form-control-sm','required'=>true, 'id' => 'address', 'placeholder'=>
                                'Enter Your Address', 'style'=>'resize:none', 'rows'=> 5]) }}
                        </div>
                    </div>

                    <div class="form-group row">
                        {{ Form::label('address', 'Address:', ['class' => 'col-sm-3']) }}
                        <div class="col-sm-3">
                            {{ Form::file('image', ['class' =>'form-control form-control-sm',
                            'required'=>false, 'id' => 'image']) }}
                        </div>
                        <div class="col-sm-2">
                            @if(auth()->user()->userInfo!= null && auth()->user()->userInfo->image != null &&
                                 file_exists(public_path().'/uploads/user/'.auth()->user()->userInfo->image))
                                <img src="{{ asset('uploads/user/'.auth()->user()->userInfo->image) }}" class="img img-fluid img-circle" />
                            @else
                                <img src="{{ asset('images/user.png') }}" alt=""  class="img img-fluid img-circle">
                            @endif
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="reset" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-redo"></i>
                        Reset
                    </button>
                    <button type="submit" class="btn btn-success">
                          <i class="fa fa-paper-plane"></i>
                        Save changes
                    </button>
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>